# fly.toml app configuration file generated for comp7940-group on 2024-03-26T16:37:03+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'comp7940-group'
primary_region = 'hkg'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[[services]]
  internal_port = 8000
  protocol = 'tcp'

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.ports]]
    handlers = ["http"]
    port = 80

[[vm]]
  size = 'shared-cpu-1x'

